// <auto-generated />
using System;
using BoardGameApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameApp.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20230726153532_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardGameApp.Models.BoardGameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherModelId");

                    b.ToTable("BoardGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Science? Military? What will you draft to win this head-to-head version of 7 Wonders?",
                            ImageURL = "https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__itemrep/img/x5L93n_pSsxfFZ0Ir-JqtjLf-Jw=/fit-in/246x300/filters:strip_icc()/pic2576399.jpg",
                            Name = "7 Wonders Dual",
                            PublisherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Craftsmen, scholars & monks can help you reign supreme—but who will turn up to help?",
                            ImageURL = "https://cf.geekdo-images.com/nagl1li6kYt9elV9jbfVQw__itemrep/img/oYYWKekDiHllrWnFNef7En3gP4c=/fit-in/246x300/filters:strip_icc()/pic6228507.jpg",
                            Name = "Orleans",
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Collect gold nuggets while avoiding the dragon watching over the hoard. ",
                            ImageURL = "https://cf.geekdo-images.com/BHLjzl2saSCs497dgIkUYA__itemrep/img/3drFnqWEU9H16NCoRWDAOtnTkiI=/fit-in/246x300/filters:strip_icc()/pic5986895.jpg",
                            Name = "My Gold Mine",
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Explore the Continent, upgrade your skills, and fight monsters/witchers for trophies.",
                            ImageURL = "https://cf.geekdo-images.com/tQVVSXcmYLvAoI28cp-2Tg__itemrep/img/rxCXKwIjRmHKwONcIo5Ja7iTiKc=/fit-in/246x300/filters:strip_icc()/pic5974859.jpg",
                            Name = "The Witcher: Old World",
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "You are the President of the United States, attempting to govern in a new millennium",
                            ImageURL = "https://cf.geekdo-images.com/xneRUjohOxhdjMhLb6DUAg__itemrep/img/VObDSJEgrYTfB80Wytebf5r4fPM=/fit-in/246x300/filters:strip_icc()/pic6977091.jpg",
                            Name = "Mr. President: The American Presidency",
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Mutating diseases are spreading around the world - can your team save humanity?",
                            ImageURL = "https://cf.geekdo-images.com/-Qer2BBPG7qGGDu6KcVDIw__itemrep/img/Wxe36yaTzpiIVhEefHOYzFv7Ucc=/fit-in/246x300/filters:strip_icc()/pic2452831.png",
                            Name = "Pandemic Legacy: Season 1",
                            PublisherId = 2
                        });
                });

            modelBuilder.Entity("BoardGameApp.Models.PublisherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Repos Production"
                        },
                        new
                        {
                            Id = 2,
                            Name = "dlp games"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IELLO, KOSMOS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CD Projekt RED, Go On Board"
                        });
                });

            modelBuilder.Entity("BoardGameApp.Models.BoardGameModel", b =>
                {
                    b.HasOne("BoardGameApp.Models.PublisherModel", null)
                        .WithMany("BoardGame")
                        .HasForeignKey("PublisherModelId");
                });

            modelBuilder.Entity("BoardGameApp.Models.PublisherModel", b =>
                {
                    b.Navigation("BoardGame");
                });
#pragma warning restore 612, 618
        }
    }
}
